# Site settings
title: "Interpreting MNIST with ChatGPT: a project"
description: "A short description of your site"
baseurl: "/" # The subpath of your site, e.g. /blog
url: "https://arkleseisure.github.io" # Your GitHub Pages URL

# GitHub settings
github_username: Arkleseisure
repository: yourrepositoryname

# Author settings
author:
  name: "Sean Herrington"
  email: "hughsean.herrington@gmail.com"

# Social links (optional)
social:
  twitter: yourtwitterhandle
  github: yourusername
  linkedin: yourlinkedinprofile

# Build settings
markdown: kramdown
theme: minima # This is a common GitHub Pages theme. You can change it to another supported theme.
plugins:
  - jekyll-feed

# Customization (optional)
# Add any other settings for layouts, styles, or content here
