# Site settings
title: "Automating interpretability with ChatGPT"
description: "A project aiming to interpret the functionality of neural networks from end to end."
baseurl: "/" # The subpath of your site, e.g. /blog
url: "https://arkleseisure.github.io"

# GitHub settings
github_username: Arkleseisure

# Author settings
author:
  name: "Sean Herrington"
  email: "hughsean.herrington@gmail.com"

# Social links
social:
  github: github.com/Arkleseisure

# Build settings
markdown: kramdown
theme: minima # This is a common GitHub Pages theme. You can change it to another supported theme.
plugins:
  - jekyll-feed

# Add any other settings for layouts, styles, or content here
